# @name getNotes
GET http://localhost:3000/notes

###

// SKAPA NOTE
POST http://localhost:3000/notes
Content-Type: application/json

{
  "name": "Dokument 1",
  "notes": "Här ska det stå info om allt möjligt!"
}

###