# @name getNotes
GET http://localhost:3000/notes

###


// HÄMTA SPECIFIK NOTE

GET http://localhost:3000/notes/8


###



// SKAPA NOTE
POST http://localhost:3000/notes/
Content-Type: application/json

{
  "name": "skrivbord",
  "note": "Här ska det stå info om allt möjligt!",
  "userId": "34"
}

###

DELETE http://localhost:3000/notes/10

###


// SKAPA USER
POST http://localhost:3000/users/notes/notesuser
Content-Type: application/json

{
  
  "name": "Anna Andersson",
  "email": "annaandersson@mail.com",
  "password": "test"

}

###


// HÄMTA USERS

GET http://localhost:3000/users/notes/notesuser


###



// LOGGA IN USER // VID FEL LÖSENORD SÅ SKALL SVARA MED 401
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "emilia@mail.com",
  "password": "test"
}

###